
package Client;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.URI;
import java.awt.Desktop;
import java.net.URL;
import java.util.ArrayList;
import java.util.Vector;

import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

import Objects.Film;
import Objects.FilmShowTimes;
import Server.server;

public class Details extends javax.swing.JDialog {

    /**
     * Creates new form Details
     */
	private static int idFilm;
	private String date;
	private String filmNameChosen;
	private String casts;
	private Film film;
    public Details(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        idFilm = client.idFilmChosen;
        date = client.date;
		film = server.getFilmDetails(idFilm);
        filmNameChosen = client.filmNameChosen;
        casts = "";
        initComponents();
     // implement UI for this function
//		setModelShowtime(server.getShowTimes(client.idCinemaChosen, client.date));
        this.setLocationRelativeTo(null);
        for(int i = 0; i < server.getShowTimes(client.idCinemaChosen, client.date).size(); i++) {
        	System.out.print("time:  " + i + " " + server.getShowTimes(client.idCinemaChosen, client.date).get(i).getShowTimes());
        }
        try {
        	URL url = new URL(film.getGraphicUrl());
        	System.out.println(url);
            ImageIcon icon = new ImageIcon(url);
            graphic_URL.setIcon(icon);
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println(e);
        }
        
//        graphic_URL.setIcon(new javax.swing.ImageIcon(".\\img\\film-preview.png"));
        btn_viewTrailer.setIcon(new javax.swing.ImageIcon(".\\img\\btn-viewTrailer.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Details = new javax.swing.JPanel();
        Sidebar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        graphic_URL = new javax.swing.JLabel();
        btn_viewTrailer = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_imdb_score = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_rotten_tomatoes_score = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Infomation = new javax.swing.JPanel();
        lbl_movie_name = new javax.swing.JLabel();
        lbl_title_en = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_description = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txt_actor = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_gerne = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_country = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_showtimes = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_review = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1210, 760));

        Details.setPreferredSize(new java.awt.Dimension(1080, 720));

        Sidebar.setBackground(new java.awt.Color(16, 16, 16));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Thông tin chi tiết");

        graphic_URL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btn_viewTrailer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_viewTrailer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txt_imdb_score.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_imdb_score.setForeground(new java.awt.Color(255, 204, 255));
        txt_imdb_score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_imdb_score.setText("7/10");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("IMDB");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txt_rotten_tomatoes_score.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_rotten_tomatoes_score.setForeground(new java.awt.Color(255, 204, 255));
        txt_rotten_tomatoes_score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_rotten_tomatoes_score.setText("58%");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Rotten Tomatoes");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(graphic_URL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SidebarLayout.createSequentialGroup()
                                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_imdb_score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_rotten_tomatoes_score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btn_viewTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphic_URL, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_viewTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addComponent(txt_imdb_score, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addComponent(txt_rotten_tomatoes_score, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Infomation.setBackground(new java.awt.Color(255, 249, 254));

        lbl_movie_name.setBackground(new java.awt.Color(51, 51, 51));
        lbl_movie_name.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lbl_movie_name.setForeground(new java.awt.Color(204, 0, 153));
        lbl_movie_name.setText("Anh Em Super Mario");
        lbl_movie_name.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lbl_title_en.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_title_en.setForeground(new java.awt.Color(102, 102, 102));
        lbl_title_en.setText("The Super Mario Bros. Movie");
        lbl_title_en.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nội dung:");

        txt_description.setBackground(new java.awt.Color(255, 249, 254));
        txt_description.setColumns(20);
        txt_description.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_description.setForeground(new java.awt.Color(102, 102, 102));
        txt_description.setLineWrap(true);
        txt_description.setRows(5);
        txt_description.setTabSize(4);
        txt_description.setText("A plumber named MarioCuộc phiêu lưu đến Vương quốc Nấm của anh chàng thợ sửa ống nước Mario và quá trình anh vươn lên trở thành một huyền thoại.");
        txt_description.setWrapStyleWord(true);
        txt_description.setBorder(null);
        txt_description.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_description.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txt_description.setEnabled(false);
        jScrollPane1.setViewportView(txt_description);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Diễn viên & Đoàn làm phim:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txt_actor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_actor.setForeground(new java.awt.Color(102, 102, 102));
        txt_actor.setText("Chris Pratt, Anna Taylor-Joy, Charlie Day, Jack Black,...");
        txt_actor.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Quốc gia:");

        txt_gerne.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_gerne.setForeground(new java.awt.Color(102, 102, 102));
        txt_gerne.setText("Hài, Hoạt Hình, Phiêu Lưu, Gia Đình");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Thể loại:");

        txt_country.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_country.setForeground(new java.awt.Color(102, 102, 102));
        txt_country.setText("Mỹ");

        tbl_showtimes.setFont(new java.awt.Font("San Francisco Text Regular G1", 0, 16)); // NOI18N
        tbl_showtimes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_showtimes.setRowHeight(40);
        tbl_showtimes.setSelectionBackground(new java.awt.Color(255, 245, 255));
        jScrollPane2.setViewportView(tbl_showtimes);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 153));
        jLabel11.setText("Lịch chiếu phim:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Bình luận từ người xem:");

        txt_review.setBackground(new java.awt.Color(255, 249, 254));
        txt_review.setColumns(20);
        txt_review.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_review.setForeground(new java.awt.Color(102, 102, 102));
        txt_review.setLineWrap(true);
        txt_review.setRows(5);
        txt_review.setTabSize(4);
        txt_review.setText("- Mario và Luigi đều có nỗi sợ để vượt qua, vs Mario thì a cực ghét nấm nhưng phải ăn nấm để cứu e trai, Luigi thì cũng phải trở nên dũng cảm. Công chúa Peach tưởng chừng là nvat đc cứu nhưng thực ra chính là ng dạy mario thành hero. ncl nhiều góc nhìn hay từ game");
        txt_review.setWrapStyleWord(true);
        txt_review.setBorder(null);
        txt_review.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_review.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txt_review.setEnabled(false);
        jScrollPane3.setViewportView(txt_review);

        javax.swing.GroupLayout InfomationLayout = new javax.swing.GroupLayout(Infomation);
        Infomation.setLayout(InfomationLayout);
        InfomationLayout.setHorizontalGroup(
            InfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfomationLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(InfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_movie_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_title_en, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_actor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfomationLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_gerne, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_country, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        InfomationLayout.setVerticalGroup(
            InfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfomationLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_movie_name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_title_en, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_country, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_gerne, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_actor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout DetailsLayout = new javax.swing.GroupLayout(Details);
        Details.setLayout(DetailsLayout);
        DetailsLayout.setHorizontalGroup(
            DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsLayout.createSequentialGroup()
                .addComponent(Sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Infomation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DetailsLayout.setVerticalGroup(
            DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Infomation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Details, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Details, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//    	System.out.println("hello id: " + idFilm);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	
                Details dialog = new Details(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public static int getIdFilm() {
		return idFilm;
	}

	public static void setIdFilm(int idFilm) {
		idFilm = idFilm;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Details;
    private javax.swing.JPanel Infomation;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JLabel btn_viewTrailer;
    private javax.swing.JLabel graphic_URL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_movie_name;
    private javax.swing.JLabel lbl_title_en;
    private javax.swing.JTable tbl_showtimes;
    private javax.swing.JLabel txt_actor;
    private javax.swing.JLabel txt_country;
    private javax.swing.JTextArea txt_description;
    private javax.swing.JLabel txt_gerne;
    private javax.swing.JLabel txt_imdb_score;
    private javax.swing.JTextArea txt_review;
    private javax.swing.JLabel txt_rotten_tomatoes_score;
    // End of variables declaration//GEN-END:variables
}
